- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'conexion-apptestphp'
    appType: 'webApp'
    WebAppName: 'warehouse-inventory-system'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'